version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: diaryttbotdb
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
